add full code

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -37,12 +37,18 @@ jobs:
         run: |
           echo "$SSH_KEY" > key.pem
           chmod 600 key.pem
+
           ssh -o StrictHostKeyChecking=no -i key.pem $SSH_USER@$SSH_HOST << EOF
             docker pull ghcr.io/andrey18051/taxi_test:${{ steps.build_test.outputs.image_tag }}
             docker stop taxi_test || true
             docker rm taxi_test || true
-            docker run --name taxi_test -d --network host --restart unless-stopped ghcr.io/andrey18051/taxi_test:${{ steps.build_test.outputs.image_tag }}
-            echo "TEST deployed!"
+            docker run --name taxi_test -d --network host --restart unless-stopped \
+              ghcr.io/andrey18051/taxi_test:${{ steps.build_test.outputs.image_tag }}
+
+            # Создаём символическую ссылку внутри контейнера
+            docker exec taxi_test php artisan storage:link || echo "storage:link already exists or failed (ignore)"
+
+            echo "TEST deployed and storage:link created!"
           EOF
 
   build-work:
@@ -87,5 +93,9 @@ jobs:
             docker stop taxi_work || true
             docker rm taxi_work || true
             docker run --name taxi_work -d --network host --restart unless-stopped ghcr.io/andrey18051/taxi_work:$TAG
+
+          # Создаём символическую ссылку внутри контейнера
+            docker exec taxi_test php artisan storage:link || echo "storage:link already exists or failed (ignore)"
+
             echo "PRODUCTION deployed!"
           EOF
